### ISSUE TITLE
How could I adhere more to SOLID principles?

### ISSUE THREAD

**Issue by mtdvlpr** [mtDvlpr/java-assignments#1]

**Comment by wimmelstein** [comment]
Well, the SOLID principle is very nice. But this is the very first assignment, and we should not worry too much about solid. This will be different if we come to the University project, where we do need it. 
The fifth principle in SOLID is the Dependency Inversion Principle, which is something to the effect of programming to an interface instead of an implementation. That would come in handy if you have more than one model class. In this case you have only one, so it's not necessary. Also, we have not covered interfaces just yet.
I suggest you exercise patience and follow the course as it comes, and be sure to ask me these questions during the lessons.
